name: Pipeline A

on:
  push:
    branches:
      - TestBranch

jobs:
  job_A:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 (Generate value)
        run: echo "http://www.google.com" > output.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-output-data
          path: output.txt
